# Generated by Django 2.0.2 on 2018-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
