# Generated by Django 2.0.2 on 2018-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
        migrations.AddField(
            model_name='note',
            name='uid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
