# Generated by Django 2.0.2 on 2018-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180502_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='photoURL',
            field=models.CharField(default='', max_length=255),
        ),
    ]
